import { useTranslation } from 'react-i18next';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Card } from '@/components/ui/card';

export default function TermsOfService() {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto px-4 py-24">
        <Card className="max-w-4xl mx-auto p-8 md:p-12">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: December 14, 2024</p>

          <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using CopyMonster ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground">
                CopyMonster is an AI-powered copywriting platform that provides automated content generation services through specialized AI agents. The Service includes, but is not limited to, generating marketing copy, sales pages, emails, advertisements, and other promotional content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
              <h3 className="text-xl font-medium mb-2">3.1 Registration</h3>
              <p className="text-muted-foreground mb-4">
                You must create an account to use our Service. You agree to provide accurate and complete information and keep your account credentials secure.
              </p>
              <h3 className="text-xl font-medium mb-2">3.2 Account Responsibility</h3>
              <p className="text-muted-foreground">
                You are responsible for all activities that occur under your account. Notify us immediately of any unauthorized use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Subscription and Payment</h2>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Subscriptions are billed monthly or annually as selected</li>
                <li>Credits are allocated based on your subscription plan</li>
                <li>Unused credits do not roll over to the next billing period</li>
                <li>Refunds are provided according to our refund policy</li>
                <li>We reserve the right to modify pricing with 30 days notice</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Acceptable Use</h2>
              <p className="text-muted-foreground mb-4">You agree NOT to use the Service to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Generate illegal, harmful, or fraudulent content</li>
                <li>Create misleading or deceptive advertising</li>
                <li>Violate intellectual property rights of others</li>
                <li>Distribute malware or engage in phishing</li>
                <li>Harass, abuse, or harm other users</li>
                <li>Attempt to reverse engineer our AI systems</li>
                <li>Resell or redistribute the Service without authorization</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Intellectual Property</h2>
              <h3 className="text-xl font-medium mb-2">6.1 Our Content</h3>
              <p className="text-muted-foreground mb-4">
                The Service, including its AI models, interface, and documentation, is owned by CopyMonster and protected by intellectual property laws.
              </p>
              <h3 className="text-xl font-medium mb-2">6.2 Your Content</h3>
              <p className="text-muted-foreground">
                You retain ownership of content you input into the Service. Content generated by our AI agents for your use belongs to you, subject to these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. AI-Generated Content Disclaimer</h2>
              <p className="text-muted-foreground">
                Content generated by our AI agents is provided "as is." While we strive for high quality, we do not guarantee that AI-generated content will be error-free, appropriate for all purposes, or achieve specific results. You are responsible for reviewing and editing all content before use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, COPYMONSTER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU IN THE TWELVE MONTHS PRECEDING THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
              <p className="text-muted-foreground">
                We may suspend or terminate your account for violations of these Terms. You may cancel your subscription at any time through your account settings. Upon termination, your access to the Service will cease, but data may be retained as required by law.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We may modify these Terms at any time. Material changes will be communicated via email or through the Service. Continued use after changes constitutes acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
              <p className="text-muted-foreground">
                These Terms are governed by the laws of Brazil. Any disputes shall be resolved in the courts of São Paulo, Brazil.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Contact</h2>
              <p className="text-muted-foreground">
                For questions about these Terms, contact us at:
              </p>
              <p className="text-muted-foreground mt-2">
                Email: legal@copymonster.me<br />
                Address: São Paulo, Brazil
              </p>
            </section>
          </div>
        </Card>
      </main>
      <Footer />
    </div>
  );
}